### PR TITLE
relative probably wont merge this but just in...

### PR DESCRIPTION
**Pull request by looskie**
relative probably wont merge this but just in case he does at like 12am and decides hmm, maybe a switch case right here would be pretty nice, and then also think to himself, this could have a performance boost too. As he did say, "I am *new line* not *new line* using *new line* tha *new line* t *new line* holy *new line* fuck" my hopes are low, but still there.

### CODE REVIEW

**Comment by looskie** [comment]
LMAO worth a shot

**Comment by relative** [comment]
holy shit you left the `console.log('cum')` in it i'm definitely not merging this

**Comment by relative** [comment]
plus you haven't followed my commit guidelines you're missing a scope and the first line of the message is too long so it got cut off omfg

**Comment by looskie** [comment]
> plus you haven't followed my commit guidelines you're missing a scope and the first line of the message is too long so it got cut off omfg

ill be back >:(

**Comment by relative** [comment]
no i sitll wont merge it please stop

**Pull request closed without merging**
